name: Deploy Workflow

on:
  workflow_run:
    workflows:
      - Publish Build Artifacts
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy_single_environment.yaml'
      - '.github/workflows/deploy_environments.yaml'
      - 'cd/environments.yaml'


concurrency:
  group: deploy

permissions:
  id-token: write
  contents: read


jobs:
  deploy-dev:
    name: Dev Environment Deployment
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    uses: ./.github/workflows/deploy_single_environment.yaml
    with:
      envId: 'dev'
      projectId: ${{ toLower(replace(github.repository, '^[^/]+/', '')) }}

